name: Manual Terraform Automation

on:
  workflow_dispatch:
    inputs:
      terraform_directory:
        description: 'Terraform configuration directory'
        required: true
        default: '.'

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.1.0

      - name: Terraform Init
        run: terraform init ${{ github.event.inputs.terraform_directory }}

      - name: Terraform Plan
        run: terraform plan -out=tfplan ${{ github.event.inputs.terraform_directory }}

      - name: Terraform Apply
        run: terraform apply tfplan ${{ github.event.inputs.terraform_directory }}
        env:
          TF_VAR_aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          TF_VAR_aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
